from __future__ import annotations

from data_pipeline.crawler.brands.generic_official import OfficialBrandConfig

COMMON = {
    'ingredients': ('Ingredients', 'Ingredient List', 'Full Ingredients', 'Ingredients List'),
    'key_ingredients': ('Key Ingredients', 'Highlighted Ingredients', 'Hero Ingredients'),
    'usage': ('How to Use', 'How To Use', 'Directions', 'Usage'),
    'warnings': ('Warnings', 'Warning', 'Caution', 'Cautions', 'Precautions'),
    'benefits': ('Benefits', 'Key Benefits', 'Features & Benefits', 'Key Features & Benefits', 'What It Does'),
    'skin_types': ('Skin Type', 'Skin Types', 'Suitable For'),
    'concerns': ('Concern', 'Concerns', 'Skin Concerns', 'Targets'),
    'texture': ('Texture',),
}

LOREAL_CATEGORY_MAP = {
    'cleanser': 'cleanser',
    'cleansers': 'cleanser',
    'face-wash': 'cleanser',
    'face-cleanser': 'cleanser',
    'toner': 'toner',
    'toners': 'toner',
    'serum': 'serum',
    'serums': 'serum',
    'face-serum': 'serum',
    'moistur': 'moisturizer',
    'face-moisturizer': 'moisturizer',
    'sunscreen': 'sunscreen',
    'sun': 'sunscreen',
    'spf': 'sunscreen',
    'exfol': 'exfoliant',
    'scrub': 'exfoliant',
    'mask': 'mask',
    'eye': 'eye_care',
    'lip': 'lip_care',
    'body': 'body_care',
}

BRAND_CONFIGS: dict[str, OfficialBrandConfig] = {
    'cerave': OfficialBrandConfig(
        slug='cerave', brand_name='CeraVe', base_url='https://www.cerave.com', official_url='https://www.cerave.com',
        sitemap_urls=('/sitemap.xml',),
        listing_urls=(
            '/skincare',
            '/skincare/cleansers',
            '/skincare/moisturizers',
            '/skincare/facial-serums',
            '/skincare/sunscreen',
            '/skincare/acne',
            '/skincare/body-care',
        ),
        product_path_patterns=(r'/skincare/(?:cleansers|moisturizers|facial-serums|sunscreen|acne|baby|body-care)/[^/?#]+$',),
        exclude_url_patterns=(r'/articles/', r'/ingredients/', r'/skin-smarts/'),
        category_path_map={'/cleansers/':'cleanser','/moisturizers/':'moisturizer','/facial-serums/':'serum','/sunscreen/':'sunscreen','/body-care/':'body_care'},
        section_headings=COMMON,
    ),
    'the-ordinary': OfficialBrandConfig(
        slug='the-ordinary', brand_name='The Ordinary', base_url='https://theordinary.com', official_url='https://theordinary.com',
        sitemap_urls=('/sitemap.xml', '/en-us/sitemap.xml'),
        listing_urls=(
            '/en-us/category/skincare',
            '/en-us/category/skincare/cleansers',
            '/en-us/category/skincare/exfoliators',
            '/en-us/category/skincare/serums',
            '/en-us/category/skincare/moisturizers',
        ),
        product_path_patterns=(r'/en-us/[^/?#]+-\d+\.html$', r'/en-us/[^/?#]+\.html$'),
        exclude_url_patterns=(r'/category/', r'/regimen', r'/guides?/', r'/blog/'),
        category_path_map={'cleanser':'cleanser','toner':'toner','serum':'serum','moistur':'moisturizer','sunscreen':'sunscreen','exfol':'exfoliant','mask':'mask','eye':'eye_care'},
        section_headings={**COMMON, 'benefits': ('Benefits', 'Targets', 'What It Does'), 'concerns': ('Targets', 'Concern', 'Concerns')},
    ),
    'laroche-posay': OfficialBrandConfig(
        slug='laroche-posay', brand_name='La Roche-Posay', base_url='https://www.laroche-posay.us', official_url='https://www.laroche-posay.us',
        sitemap_urls=('/sitemap.xml',),
        listing_urls=(
            '/our-products',
            '/our-products/face',
            '/our-products/face/face-wash',
            '/our-products/face/face-moisturizer',
            '/our-products/face/face-serum',
            '/our-products/sun',
            '/our-products/body',
        ),
        product_path_patterns=(r'/our-products/[^?#]+$', r'/face/[^?#]+$'),
        exclude_url_patterns=(r'/article/', r'/skin-edit/', r'/ingredient/'),
        category_path_map={'cleanser':'cleanser','toner':'toner','serum':'serum','moistur':'moisturizer','sunscreen':'sunscreen','exfol':'exfoliant','mask':'mask','eye':'eye_care','lip':'lip_care','body':'body_care'},
        section_headings={**COMMON, 'benefits': ('Product Benefits', 'Benefits', 'Key Benefits')},
    ),
    'paulas-choice': OfficialBrandConfig(
        slug='paulas-choice', brand_name="Paula's Choice", base_url='https://www.paulaschoice.com', official_url='https://www.paulaschoice.com',
        sitemap_urls=('/sitemap.xml',),
        listing_urls=(
            '/skin-care-products',
            '/skin-care-products/cleansers',
            '/skin-care-products/toners',
            '/skin-care-products/exfoliants',
            '/skin-care-products/serums',
            '/skin-care-products/moisturizers',
            '/skin-care-products/sunscreen',
        ),
        product_path_patterns=(r'/[^/?#]+/\d+\.html$', r'/[^/?#]+\.html$'),
        exclude_url_patterns=(r'/expert-advice/', r'/ingredient-dictionary/', r'/category/', r'/collections/'),
        category_path_map={'cleanser':'cleanser','toner':'toner','serum':'serum','moistur':'moisturizer','sunscreen':'sunscreen','exfol':'exfoliant','mask':'mask','eye':'eye_care','lip':'lip_care','body':'body_care'},
        section_headings={**COMMON, 'benefits': ('What It Does', 'Benefits', 'Key Benefits')},
    ),
    'bioderma': OfficialBrandConfig(
        slug='bioderma', brand_name='Bioderma', base_url='https://www.bioderma.us', official_url='https://www.bioderma.us',
        sitemap_urls=('/sitemap.xml',),
        listing_urls=(
            '/en/c/all-products.html',
            '/en/c/all-products/sensibio.html',
            '/en/c/all-products/atoderm.html',
            '/en/c/all-products/hydrabio.html',
            '/en/c/all-products/sebium.html',
            '/en/c/all-products/pigmentbio.html',
            '/en/c/all-products/cicabio.html',
        ),
        product_path_patterns=(r'/en/p/[^?#]+\.html$',),
        exclude_url_patterns=(r'/expert-advice/', r'/landing/', r'/c/'),
        category_path_map={
            'micellar': 'makeup_remover',
            'cleanser': 'cleanser',
            'foaming': 'cleanser',
            'toner': 'toner',
            'serum': 'serum',
            'lotion': 'moisturizer',
            'cream': 'moisturizer',
            'balm': 'lip_care',
            'eye': 'eye_care',
            'body': 'body_care',
        },
        section_headings={
            **COMMON,
            'description': ('Detailed description', 'Description'),
            'benefits': ('Benefits', 'Product benefits'),
            'skin_types': ('For', 'Skin type', 'Skin types'),
        },
    ),
    'eucerin': OfficialBrandConfig(
        slug='eucerin', brand_name='Eucerin', base_url='https://www.eucerinus.com', official_url='https://www.eucerinus.com',
        sitemap_urls=('/sitemap.xml',),
        listing_urls=(
            '/products',
            '/products/face-care',
            '/products/body-care',
            '/products/sun-protection',
            '/products/radiant-tone',
            '/products/immersive-hydration',
            '/products/skin-balance',
        ),
        product_path_patterns=(r'/products/[^/?#]+/[^/?#]+$',),
        exclude_url_patterns=(r'/skin-concerns/', r'/about/', r'/articles?/', r'/search'),
        category_path_map=LOREAL_CATEGORY_MAP,
        section_headings={
            **COMMON,
            'description': ('About', 'Description'),
            'benefits': ('Benefits', 'Product Benefits'),
            'skin_types': ('Skin Type', 'Suitable for'),
            'concerns': ('Skin concerns', 'Skin Concern'),
        },
    ),
    'neutrogena': OfficialBrandConfig(
        slug='neutrogena', brand_name='Neutrogena', base_url='https://www.neutrogena.com', official_url='https://www.neutrogena.com',
        sitemap_urls=('/sitemap.xml',),
        listing_urls=(
            '/skin/all-skincare-products',
            '/skin/cleansers',
            '/skin/moisturizers',
            '/skin/serums',
            '/skin/sunscreens',
            '/skin/acne',
            '/skin/anti-aging',
        ),
        product_path_patterns=(r'/products/skincare/[^/?#]+$',),
        exclude_url_patterns=(r'/tips-and-advice/', r'/skin-care/', r'/collections/'),
        category_path_map=LOREAL_CATEGORY_MAP,
        section_headings={**COMMON, 'benefits': ('Benefits', 'Product Benefits', 'Key Benefits')},
    ),
    'vichy': OfficialBrandConfig(
        slug='vichy', brand_name='Vichy', base_url='https://www.vichyusa.com', official_url='https://www.vichyusa.com',
        sitemap_urls=('/sitemap.xml',),
        listing_urls=(
            '/skin-care/by-collection',
            '/skin-care/skin-care-product-type/face-serum',
            '/skin-care/skin-care-product-type/moisturizers',
            '/skin-care/skin-care-product-type/eye-care',
            '/skin-care/skin-care-concern/anti-aging',
            '/skin-care/skin-care-concern/dry-skin',
        ),
        product_path_patterns=(r'/skin-care/[^?#]+\.html$',),
        exclude_url_patterns=(r'/article/', r'/blog/', r'/start-here\.html$'),
        category_path_map=LOREAL_CATEGORY_MAP,
        section_headings={
            **COMMON,
            'benefits': ('Key Benefits', 'Benefits'),
            'skin_types': ('Skin Type', 'Skin Types'),
            'concerns': ('Skin Concern', 'Skin Concerns'),
        },
    ),
    'kiehls': OfficialBrandConfig(
        slug='kiehls', brand_name="Kiehl's", base_url='https://www.kiehls.com', official_url='https://www.kiehls.com',
        sitemap_urls=('/sitemap.xml',),
        listing_urls=(
            '/skincare/all-skincare-products/',
            '/skincare/face-moisturizers/',
            '/skincare/face-serums/',
            '/skincare/cleansers-scrubs/',
            '/skincare/toners/',
            '/skincare/sunscreen/',
            '/skincare/eye-creams-and-serums/',
        ),
        product_path_patterns=(r'/skincare/[^?#]+/\d+\.html$', r'/skincare/[^?#]+/[^/?#]+/\d+\.html$'),
        exclude_url_patterns=(r'/customer-service/', r'/blog/', r'/offers/'),
        category_path_map=LOREAL_CATEGORY_MAP,
        section_headings={
            **COMMON,
            'description': ('What It Is', 'What It Is:', 'Description'),
            'benefits': ('What It Does', 'Benefits', 'Key Benefits'),
            'key_ingredients': ('Key Ingredients', 'Highlighted Ingredients', 'Key Ingredient'),
        },
    ),
    'laneige': OfficialBrandConfig(
        slug='laneige', brand_name='LANEIGE', base_url='https://us.laneige.com', official_url='https://us.laneige.com',
        sitemap_urls=('/sitemap.xml',),
        listing_urls=(
            '/collections/skincare',
            '/collections/moisturizers',
            '/collections/serums-essences',
            '/collections/cleansers',
            '/collections/masks',
            '/collections/lip-care',
        ),
        product_path_patterns=(r'/products/[^/?#]+$',),
        exclude_url_patterns=(r'/blogs/', r'/pages/', r'/collections/'),
        category_path_map=LOREAL_CATEGORY_MAP,
        section_headings={
            **COMMON,
            'description': ('Summary', 'Product Overview', 'Description'),
            'key_ingredients': ('Key Ingredient', 'Key Ingredients'),
            'skin_types': ('Skin Type', 'Skin Types'),
        },
    ),
    'innisfree': OfficialBrandConfig(
        slug='innisfree', brand_name='innisfree', base_url='https://us.innisfree.com', official_url='https://us.innisfree.com',
        sitemap_urls=('/sitemap.xml',),
        listing_urls=(
            '/collections/skincare',
            '/collections/serums',
            '/collections/moisturizers',
            '/collections/cleansers',
            '/collections/sunscreen',
            '/collections/masks',
        ),
        product_path_patterns=(r'/products/[^/?#]+$',),
        exclude_url_patterns=(r'/blogs/', r'/pages/', r'/collections/'),
        category_path_map=LOREAL_CATEGORY_MAP,
        section_headings={
            **COMMON,
            'description': ('Product Overview', 'Summary', 'Description'),
            'key_ingredients': ('Key Ingredient', 'Key Ingredients'),
            'skin_types': ('Skin Type', 'Skin Types'),
        },
    ),
    'first-aid-beauty': OfficialBrandConfig(
        slug='first-aid-beauty', brand_name='First Aid Beauty', base_url='https://www.firstaidbeauty.com', official_url='https://www.firstaidbeauty.com',
        sitemap_urls=('/sitemap.xml',),
        listing_urls=(
            '/collections/all-products',
            '/collections/cleansers',
            '/collections/moisturizers',
            '/collections/serums-treatments',
            '/collections/masks',
            '/collections/body-care',
        ),
        product_path_patterns=(r'/products/[^/?#]+$',),
        exclude_url_patterns=(r'/blogs/', r'/pages/', r'/collections/'),
        category_path_map=LOREAL_CATEGORY_MAP,
        section_headings={
            **COMMON,
            'description': ('Description', 'Product Details', 'About'),
            'benefits': ('Benefits', 'Why We Love It', 'Key Benefits'),
        },
    ),
}
